#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib" }

use lib '/data/web/mojo/mojo-storage/lib';
use lib '/data/web/mojo/Mojolicious-Plugin-DateSimple/lib';

# Start command line interface for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('App::Comics');
