#!/bin/bash
#
# This software is copyright (c) 2013 by Andy Gorman.
#
# This is free software; you can redistribute it and/or modify it under the same
# terms as the Perl 5 programming language system itself.

PERLBREW_HOME=${PERLBREW_HOME:=$HOME/.perlbrew}

function error() {
    echo $1
    exit 1;
}

if [ ! -f "$PERLBREW_HOME/init" ]; then
    error "no such file: $PERLBREW_HOME/init";
fi

source $"$PERLBREW_HOME/init"

if [ -z $PERLBREW_ROOT ]; then
    error "unable to load PERLBREW_ROOT environment variable"
fi

BASHRC="$PERLBREW_ROOT/etc/bashrc"

if [ ! -f $BASHRC ]; then
    error "no such file $PERLBREW_ROOT/etc/bashrc"
fi

source $BASHRC

DIR=$(dirname $0)
exec perlbrew exec $DIR/comics download -l
